@startuml ChainBuy
top to bottom direction

skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
' Classes base
class Usuário {
    -nome
    -email
}

class Produto {
    -nome   
    -preco
    -estoque
}

class EspecificaçãoProduto {
    -fabricante
    -formato
    -peso
    -altura
    -largura
    -comprimento
    -diametro
    -prazoGarantia
    -informacoesAdicionais
    -marca
}

class Cliente {
    -id
    -nome
    -email
    -senha
    -telefone
}

class EnderecoEntrega {
    -id
    -logradouro
    -numero
    -complemento
    -bairro
    -cidade
    -estado
    -cep
}

class Vendedor {
    -id
    -nome
    -email
    -senha
    -cnpj
    -telefone
}

class Pedido {
    -id
    -descricao
    -dataCriacao
    -status
    -valorTotal
}

class PedidoItem {
    -id
    -quantidade
    -precoUnitario
}

class MetodoPagamento {
    -id
    -tipo
}

class Carrinho {
    -id
    -dataCriacao
}

class CarteiraDigital {
    -id
    -enderecoWallet
    -saldo
}

class Cartão {
    -id
    -numero
    -nomeTitular
    -validade
    -cvv
    -bandeira
}

class Entrega {
    -id
    -status
    -dataPrevista
    -codigoRastreamento
}

class Review {
    -id
    -nota
    -comentario
    -data
}

class TransaçaoBlockChain {
    -id
    -txHash
    -payload
    -timestamp
    -status
}

MetodoPagamento <|-- Cartão
MetodoPagamento <|-- CarteiraDigital
Usuário <|-- Cliente
Usuário <|-- Vendedor

Vendedor "1" --> "0..*" Produto : anuncia >
Cliente "1" --> "0..*" Pedido : realiza >
PedidoItem "1" -- "1" Produto
Produto "1" -- "0..*" PedidoItem
Carrinho "1" --> "1" Pedido : gera >
Cliente "1" --> "0..*" Review : escreve >
Pedido "1" -- "1" Entrega

Produto "1" o-- "0..*" Review : recebe >
Carrinho "1" o-- "0..*" PedidoItem : contém >
CarteiraDigital o-- TransaçaoBlockChain : Realiza
Entrega "1" o-- "1" EnderecoEntrega

Entrega "1" ..> "1..*" TransaçaoBlockChain
Pedido "1" ..> "1" MetodoPagamento : utiliza >
Pedido "1" ..> "1..*" TransaçaoBlockChain
Review "1" ..> "1" TransaçaoBlockChain

Cliente "1" *-- "0..*" EnderecoEntrega : possui >
Cliente "1" *-- "1" Carrinho : possui >
Produto "1" *-- "1" EspecificaçãoProduto
Pedido "1" *-- "1..*" PedidoItem: contém >
@enduml
