@startuml ChainBuy
top to bottom direction

skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
' Classes base
class Usuário {
    -nome: String
    -email: String
}

class Produto {
    -nome: String    
    -preco: BigDecimal
    -estoque: Integer
}

class EspecificaçãoProduto {
    -fabricante: String
    -formato: enum
    -peso: BigDecimal
    -altura: BigDecimal
    -largura: BigDecimal
    -comprimento: BigDecimal
    -diametro: BigDecimal
    -garantiaExpira: Date
    -marca: String
}

class Cliente {
    -id: Long
    -nome: String
    -email: String
    -senha: String
    -telefone: String
}

class EnderecoEntrega {
    -id: Long
    -logradouro: String
    -numero: String
    -complemento: String
    -bairro: String
    -cidade: String
    -estado: String
    -cep: String
}

class Vendedor {
    -id: Long
    -nome: String
    -email: String
    -senha: String
    -cnpj: String
    -telefone: String
}

class Pedido {
    -id: Long
    -descricao: String
    -dataCriacao: Date
    -status: String
    -valorTotal: BigDecimal
}

class PedidoItem {
    -id: Long
    -quantidade: Integer
    -precoUnitario: BigDecimal
}

class MetodoPagamento {
    -id: Long
    -tipo: String
}

class Carrinho {
    -id: Long
    -dataCriacao: Date
}

class CarteiraDigital {
    -id: Long
    -enderecoWallet: String
    -saldo: BigDecimal
}

class Cartão {
    -id: Long
    -numero: String
    -nomeTitular: String
    -validade: String
    -cvv: String
    -bandeira: String
}

class Entrega {
    -id: Long
    -status: String
    -dataPrevista: Date
    -codigoRastreamento: String
}

class Review {
    -id: Long
    -nota: Integer
    -comentario: String
    -data: Date
}

class TransaçaoBlockChain {
    -id: Long
    -txHash: String
    -payload: String
    -timestamp: Date
    -status: String
}

MetodoPagamento <|-- Cartão
MetodoPagamento <|-- CarteiraDigital
Usuário <|-- Cliente
Usuário <|-- Vendedor

Vendedor "1" --> "0..*" Produto : anuncia >
Cliente "1" --> "0..*" Pedido : realiza >
Produto "1" -- "0..*" PedidoItem
Carrinho "1" --> "1" Pedido : gera >
Cliente "1" --> "0..*" Review : escreve >
Pedido "1" -- "1" Entrega

Produto "1" o-- "0..*" Review : recebe >
Carrinho "1" o-- "0..*" PedidoItem : contém >
CarteiraDigital o-- TransaçaoBlockChain : Realiza
Entrega "1" o-- "1" EnderecoEntrega

Entrega "1" ..> "1..*" TransaçaoBlockChain
Pedido "1" ..> "1" MetodoPagamento : utiliza >
Pedido "1" ..> "1..*" TransaçaoBlockChain
Review "1" ..> "1" TransaçaoBlockChain

Cliente "1" *-- "0..*" EnderecoEntrega : possui >
Cliente "1" *-- "1" Carrinho : possui >
Produto "1" *-- "1" EspecificaçãoProduto
Pedido "1" *-- "1..*" PedidoItem: contém >
@enduml
