@startuml ChainBuy
top to bottom direction

skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
' Classes base
class Usuário {
    -nome: String
    -email: String
}

class Produto {
    -nome: String    
    -preco: BigDecimal
    -estoque: Integer
}

class EspecificaçãoProduto {
    -fabricante: String
    -formato: enum
    -peso: BigDecimal
    -altura: BigDecimal
    -largura: BigDecimal
    -comprimento: BigDecimal
    -diametro: BigDecimal
    -garantiaExpira: Date
    -marca: String
}

class Cliente {
    
}

class EnderecoEntrega

class Vendedor {
    
}

class Pedido {
    -descricao: String

}

class PedidoItem{
    -quantidade: Integer
    -precoUnitario: double
}

class MetodoPagamento {

}

class Carrinho

class CarteiraDigital

class Cartão

class Entrega

class Review

class TransaçaoBlockChain {
    -txHash
    -payload
    -timestamp
    -status
}

MetodoPagamento <|-- Cartão
MetodoPagamento <|-- CarteiraDigital
Usuário <|-- Cliente
Usuário <|-- Vendedor

Vendedor "1" --> "0..*" Produto : anuncia >
Cliente "1" --> "0..*" Pedido : realiza >
PedidoItem "1" -- "1..*" Produto
Carrinho "1" --> "1" Pedido : gera >
Cliente "1" --> "0..*" Review : escreve >
Pedido "1" -- "1" Entrega

Produto "1" o-- "0..*" Review : recebe >
Carrinho "1" o-- "0..*" PedidoItem : contém >
CarteiraDigital o-- TransaçaoBlockChain : Realiza
Entrega "1" o-- "1" EnderecoEntrega

Entrega "1" ..> "1..*" TransaçaoBlockChain
Pedido "1" ..> "1" MetodoPagamento : utiliza >
Pedido "1" ..> "1..*" TransaçaoBlockChain
Review "1" ..> "1" TransaçaoBlockChain

Cliente "1" *-- "0..*" EnderecoEntrega : possui >
Cliente "1" *-- "1" Carrinho : possui >
Produto "1" *-- "1" EspecificaçãoProduto
Pedido "1" *-- "1..*" PedidoItem: contém >
@enduml
