@startuml ChainBuy

' Classes base
class Usuário {
    -nome: String
    -email: String
}

class Produto {
    
}

class Cliente {

}

class Vendedor {
    
}

class Pedido {
    -descricao: String

}

class MetodoDePagamento{

}

class CarteiraDigital

class Cartão
' Herança
MetodoDePagamento <|-- Cartão
MetodoDePagamento <|-- CarteiraDigital
Usuário <|-- Cliente
Usuário <|-- Vendedor

' Associação
Vendedor --> Produto : anuncia >
Cliente --> Pedido : realiza >
Pedido --> MetodoDePagamento : possui >

' Agregação
Pedido o-- Produto : contém >

' Composição
'*--

@enduml
